"""v1.5 site pipeline regression: site/build.jc reproduces docs/ byte for byte.

The docs/ website is generated by the sitegen package from the authored
content fragments in site/content/, assembled by site/build.jc (pure
Jesun.Code, no post-processing). These tests guard the v1.5.0 claim
"the site builds itself":

- test_build_reproduces_docs: rebuild into a temp dir through the
  bootstrap interpreter and assert every generated file is byte-identical
  to docs/. Edit content or the builder, rebuild, and this stays green;
  hand-editing docs/ fails it.
- test_build_differential_bootstrap_vs_walker: the same build through the
  self-hosted walker produces the identical tree.
"""

import filecmp
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JESUN_PY = os.path.join(REPO, "jesun.py")
JESUN_JC = os.path.join(REPO, "jesun.jc")

GENERATED = [
    "index.html",
    "about.html",
    "community.html",
    "faq.html",
    "brand/index.html",
    "blog/index.html",
    "blog/v0.4.0-jpm-packages.html",
    "blog/v0.5.0-bangla-vscode.html",
    "blog/v0.6.0-fleets.html",
    "blog/v1.0.0-self-hosting.html",
    "blog/v1.1.0-native.html",
    "blog/v1.2.0-jweb.html",
    "blog/v1.3.0-frontend.html",
    "blog/v1.4.0-interop.html",
    "blog/v1.5.0-sitegen.html",
    "blog/v2.0.0-games.html",
    "sitemap.xml",
    "robots.txt",
    "llms.txt",
]


def build_tree(workdir, walker):
    """Copy site/ into workdir, run site/build.jc, return the output dir."""
    shutil.copytree(os.path.join(REPO, "site"), os.path.join(workdir, "site"))
    src = os.path.join(workdir, "site", "build.jc")
    args = [sys.executable, JESUN_PY] + ([JESUN_JC, src] if walker else [src])
    env = dict(os.environ, JESUN_CODE_SITE_BASE="out")
    proc = subprocess.run(
        args, cwd=workdir, env=env, capture_output=True, text=True, timeout=1200
    )
    tail = (proc.stdout + proc.stderr)[-600:]
    assert proc.returncode == 0, f"site build failed (walker={walker}): {tail}"
    return os.path.join(workdir, "out")


class SiteBuildTest(unittest.TestCase):
    def test_build_reproduces_docs(self):
        tmp = tempfile.mkdtemp(prefix="site_build_")
        try:
            out = build_tree(tmp, walker=False)
            for rel in GENERATED:
                got = os.path.join(out, rel)
                want = os.path.join(REPO, "docs", rel)
                self.assertTrue(os.path.isfile(got), f"build did not emit {rel}")
                self.assertTrue(
                    filecmp.cmp(got, want, shallow=False),
                    f"{rel} differs from docs/{rel}: "
                    "rebuild the site with `python3 jesun.py site/build.jc`",
                )
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_build_differential_bootstrap_vs_walker(self):
        boot_tmp = tempfile.mkdtemp(prefix="site_build_boot_")
        self_tmp = tempfile.mkdtemp(prefix="site_build_self_")
        try:
            boot_out = build_tree(boot_tmp, walker=False)
            self_out = build_tree(self_tmp, walker=True)
            for rel in GENERATED:
                self.assertTrue(
                    filecmp.cmp(
                        os.path.join(boot_out, rel),
                        os.path.join(self_out, rel),
                        shallow=False,
                    ),
                    f"{rel} differs between bootstrap and self-hosted builds",
                )
        finally:
            shutil.rmtree(boot_tmp, ignore_errors=True)
            shutil.rmtree(self_tmp, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
